### ISSUE TITLE
failed to list sessions: Agent Engine listSessions error: TypeError: (d.sessions || d || []).map is not a function

### ISSUE THREAD

**Issue by soonho2** [bhancockio/adk-fullstack-deploy-tutorial#4]
When I deploy the front end in Vercel https://riapa-cge-model-agent-development.vercel.app/, I got this error message:

❌ [ADK SESSION SERVICE] Agent Engine listSessions error: TypeError: (d.sessions || d || []).map is not a function
at k.listSessions (.next/server/app/page.js:18:7173)
at async m (.next/server/app/page.js:18:9536)
at async o (.next/server/app/page.js:18:9606)
at async f (.next/server/app/page.js:15:9845)

I checked the agent engine in GCP and there is no traffic. I guess that something is going on between the front end and back end.
Could you kindly help me to figure it out?
Any tips or advice are very appreciated.

**Comment by aidiary** [comment]
I have the same issue. This is the Vercel's Log

```
🔗 [ADK SESSION SERVICE] Agent Engine listSessions request: {
  endpoint: 'https://us-central1-aiplatform.googleapis.com/v1beta1/projects/deploy-adk-dev-xxxxx/locations/us-central1/reasoningEngines/xxxxxxxxxxx/sessions',
  method: 'GET'
}

❌ [ADK SESSION SERVICE] Agent Engine listSessions error: TypeError: (d.sessions || d || []).map is not a function
    at k.listSessions (.next/server/app/page.js:18:34856)
    at async m (.next/server/app/page.js:18:37219)
    at async o (.next/server/app/page.js:18:37289)
    at async f (.next/server/app/page.js:9:9845)

❌ [SESSION_LIST_ACTION] Error fetching active sessions: TypeError: (d.sessions || d || []).map is not a function
    at k.listSessions (.next/server/app/page.js:18:34856)
    at async m (.next/server/app/page.js:18:37219)
    at async o (.next/server/app/page.js:18:37289)
    at async f (.next/server/app/page.js:9:9845)
```

curl is OK

```
❯ curl -X GET \
     -H "Authorization: Bearer $(gcloud auth print-access-token)" \
     "https://us-central1-aiplatform.googleapis.com/v1beta1/projects/deploy-adk-dev-xxxxx/locations/us-central1/reasoningEngines/xxxxxxxxxxx/sessions"
{}
```

**Comment by soonho2** [comment]
I fixed it out to add .env.local file to the agent engine directly, since the vercel cannot find the environmental variables that I set up.

**Comment by cpatra11** [comment]
> I fixed it out to add .env.local file to the agent engine directly, since the vercel cannot find the environmental variables that I set up.

can you explain it a more please?
I tried everything but still getting the same issue-
Failed to list sessions: Bad Request

**Comment by dominicdev** [comment]
same got same error.. any fix?

**Comment by dominicdev** [comment]
okay was able to fix it

in the session-history.ts

in line 142

```
const rawSessions = responseData.sessions || responseData || [];
```

change it to

```
 const rawSessions = Array.isArray(responseData.sessions) 
          ? responseData.sessions 
          : Array.isArray(responseData) 
            ? responseData 
            : [];
```
